import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="he">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div className="fixed inset-0 -z-10">
            <Image
              src="/background.jpeg"
              alt="רקע"
              fill
              style={{ objectFit: 'cover' }}
              priority
            />
          </div>
          {children}
      </body>
    </html>
  );
}
